### ISSUE TITLE
Enable quantization by default?

### ISSUE THREAD

**Issue by czender** [conda-forge/netcdf4-feedstock#158]
### Comment:

AFAICT the netCDF quantization options are not enabled in the conda-forge netCDF library. This is distinct from #154 because the "new" compressors like Zstandard need plugins, etc, whereas quantization needs no external libraries so it is mysterious to me why it is not enabled by default. From an up-to-date Conda-forge library:
```
zender@login10:~$ which nc-config
/ccs/home/zender/anaconda/bin/nc-config
zender@login10:~$ nc-config --libdir
/ccs/home/zender/anaconda/lib
zender@login10:~$ nc-config --version
netCDF 4.9.2
zender@login10:~$ nc-config --has-quantize
no
zender@login10:~$ 
```
I build netCDF often from upstream (Unidata) snapshots and AFAICT the Autotools build machinery requires no specific options to enable quantization. So I suspect that this may be a CMake issue that affects netcdf4-feedstock builds, but not people who build with Autotools. However, CMake is not my forté so I could be missing something. In any case, it would be great if Conda-forge feedstock folks figured out how to enable quantization by default. Thanks for your efforts!

**Comment by xylar** [comment]
@czender, I believe this is meant for https://github.com/conda-forge/libnetcdf-feedstock and not for this feedstock, which is focused on the NetCDF4 python package.  If I have that right, could you close this and open an identical issue over there?

**Comment by czender** [comment]
What a blunder :) Done. Thanks @xylar
