### ISSUE TITLE
Cython dependency causes error on package build

### ISSUE THREAD

**Issue by djhoese** [conda-forge/netcdf4-feedstock#33]
When building a conda package that depends on netcdf4 but not on cython the build fails trying to look for cython>=0.19. Below is a summary of the error message:

```
netcdf4:         1.2.8-np112py36_1                  conda-forge
...
Installed /Users/davidh/anaconda/conda-bld/sift_1496944941781/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/sift-0.9.3a0-py3.6.egg
Processing dependencies for sift==0.9.3a0
Searching for cython>=0.19
Traceback (most recent call last):
  File "setup.py", line 173, in <module>
    ...
  File "/Users/davidh/anaconda/conda-bld/sift_1496944941781/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/setuptools/package_index.py", line 812, in scan_url
    self.process_url(url, True)
  File "/Users/davidh/anaconda/conda-bld/sift_1496944941781/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/setuptools/package_index.py", line 317, in process_url
    "Be sure to add all dependencies in the meta.yaml  url=%sr" % url)
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/cython/r
```

I think this is related to unidata/netcdf4-python#666 and unidata/netcdf4-python#673. I was the one who pointed out the issue in these PRs that cython was being used before pip had a chance to install it. However, I'm not sure how that should affect the conda packages. I was able to resolve the above issue by either listing `cython >=0.19` as a dependency in my meta.yaml or by removing my `netCDF4` dependency in my setup.py. Both methods build my conda package successfully.

I'm not sure why this is happening since conda should be detecting that `netCDF4` in the setup.py is in the conda environment already. My only guess is that `python setup.py install` is checking requirements (cython) of my package's requirements (netcdf4) without actually checking if they are installed. I'm sure that isn't what it is doing, but I can't explain this otherwise. The other odd thing is that I did get this message:

```
WARNING: conda-build appears to be out of date. You have version 2.1.10 but the
latest version is 2.1.15. Run

conda update -n root conda-build

to get the latest version.
```

But when I run that command it says 2.1.10 is already installed. Looks like 2.1.15 is only available through default channels. I forced the version to get it from the default channels but still get the above error about cython.

**Comment by ocefpaf** [comment]
> When building a conda package that depends on netcdf4 but not on cython the build fails trying to look for cython>=0.19

Are you building it with `conda`? A package that depends on a conda binary `netcdf4` should not try to download its dependencies. Still that is an upstream issue and it seems that a fix is in place already. Thanks for the report!
