### ISSUE TITLE
Bad OSX Images?

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/netcdf4-feedstock#4]
I'm getting the following message with the `1.2.3-np110py34_0` package for osx64:

``` pytb
Traceback (most recent call last):
  File "run_all.py", line 1, in <module>
    import glob, os, sys, unittest, netCDF4
  File "/Users/rmay/miniconda3/envs/py34/lib/python3.4/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/rmay/miniconda3/envs/py34/lib/python3.4/site-packages/netCDF4/_netCDF4.so, 2): no suitable image found.  Did find:
    /Users/rmay/miniconda3/envs/py34/lib/python3.4/site-packages/netCDF4/_netCDF4.so: malformed mach-o image: load command #13 length (0) too small in /Users/rmay/miniconda3/envs/py34/lib/python3.4/site-packages/netCDF4/_netCDF4.so
```

Rolling back to `1.2.2-np110py34_0`  at least allows me to run the test suite.

**Comment by ocefpaf** [comment]
Linux seems to be OK (Windows builds are not done yet.). I tested:

``` shell
conda create -n PY34 python=3.4 netcdf4
source activate PY34
python -c 'import netCDF4; print(netCDF4.__version__)'
1.2.3
```

> no suitable image found.

I've seen this before... Can't recall where... Could it be the new conda?

**Comment by dopplershift** [comment]
I'm now seeing this on two different OSX 10.11 machines.

**Comment by ocefpaf** [comment]
Good to know. Thanks!

Still let's leave this open.

**Comment by dopplershift** [comment]
Lovely. A bunch of other conda-forge osx packages (rasterio, pyproj, fiona, pyart) all import their compiled extensions fine.

What is special/wrong with netcdf4? Rolling back to conda-forge's 1.2.2 package also works.

**Comment by ocefpaf** [comment]
> What is special/wrong with netcdf4?

I don't own a Mac to investigate this further and I have no idea what that error means. Google suggests a re-build. I will try that soon.

**Comment by ocefpaf** [comment]
PS: Can you test the PY27 and PY35 packages to see if they suffer from the same problem?

**Comment by dopplershift** [comment]
Rebuild fixed it. Weird.

What was weird was that I was getting the same error on both 3.4 and 3.5--which led me to believe it was systemic, not just a bad build. Thanks for trying it and succeeding!

**Comment by ocefpaf** [comment]
> Thanks for trying it and succeeding!

Very few things cannot be fixed by a good Google search :wink:
