### ISSUE TITLE
pinning out of sync with libgdal...

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/netcdf4-feedstock#42]
I just tried to install the latest versions of both gdal and netcdf4, and ended up with a significant downgrade of both:

Starting from scratch:

```
$ conda install gdal
... The following NEW packages will be INSTALLED:
    gdal:      2.2.3-py27_0 conda-forge
    libgdal:   2.2.3-1      conda-forge
    libnetcdf: 4.4.1.1-10   conda-forge
```
All good (and it seems to work :-) )

But then I install try to install netcdf4:

```
$ conda install netcdf4
The following NEW packages will be INSTALLED:
    netcdf4:   1.3.1-py27_2 conda-forge
The following packages will be UPDATED:
    libnetcdf: 4.4.1.1-10   conda-forge --> 4.5.0-3       conda-forge

The following packages will be DOWNGRADED:
    gdal:      2.2.3-py27_0 conda-forge --> 1.10.1-py27_1            
    libgdal:   2.2.3-1      conda-forge --> 1.11.2-1
```
Ouch! Though they do appear to work (at least both import into python) but I need gdal >= 2.0!

The problem is that the latest build of netcdf4 is pinned to libnetcdf 4.5.*

But the latest libgdal is pinned to libnetcdf 4.4.*

I'm not sure how to keep this all in sync, but we really need to update everything that depends on, say libnetcdf at once....

AFAICT, the libgdal feedstock is still pinned to libnetcdf 4.4.*, so this isn't a "waiting for the CI" issue. And this was last built 22 days ago.

**Comment by ocefpaf** [comment]
There is a version of `netcdf4` with `libnetcdf 4.4.*` and you'll need to "help" conda by specifying it together with the gdal version you want like, `conda create --name TEST gdal=2 netcdf4`, for example.

We are not in a hurry to build anything else with `libnetcdf 4.5.0` b/c that version will force us to drop Python 2.7 on Windows. So the other packages will take a while to load.

PS: note that nothing is wrong with your previous commands, conda is just trying to "optimize" it for you. You need to me explicit about `gdal` to get the right stack of packages though.
