### ISSUE TITLE
Rebuild with dependency on libnetcdf=4.6.0?

### ISSUE THREAD

**Issue by shoyer** [conda-forge/netcdf4-feedstock#45]
Is there any reason not to update this recipe to use libnetcdf 4.6.0 instead of 4.5.0?

It appears that the recipe for libnetcdf has been updated (https://github.com/conda-forge/libnetcdf-feedstock/blob/master/recipe/meta.yaml) but not this recipe.

This would fix a downstream issue for xarray: https://github.com/pydata/xarray/issues/2050

**Comment by ocefpaf** [comment]
We want to use 4.6.1 but that is failing at the moment. I'll try to fix that today.

**Comment by ocefpaf** [comment]
This is done but we may have to pull the binaries if I cannot sort https://github.com/conda-forge/libnetcdf-feedstock/issues/44 out first.
