### ISSUE TITLE
ValueError: cannot reshape array of size 1 into shape (7,)

### ISSUE THREAD

**Issue by ReimarBauer** [conda-forge/netcdf4-feedstock#58]
Issue:

<br/>
conda install -c conda-forge netcdf4
Solving environment: done

## Package Plan ##

  environment location: /home/user/miniconda3/envs/mssenv3

  added / updated specs: 
    - netcdf4

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2018.8.24  |       ha4d7672_0         136 KB  conda-forge
    netcdf4-1.4.1              |   py36h62672b6_0         2.0 MB  conda-forge
    certifi-2018.8.24          |           py36_1         139 KB  conda-forge
    openssl-1.0.2p             |       h470a237_0         3.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         5.8 MB

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0         --> 2018.8.24-ha4d7672_0 conda-forge
    certifi:         2018.8.24-py36_1     --> 2018.8.24-py36_1     conda-forge
    netcdf4:         1.4.0-py36ha06eab4_1 --> 1.4.1-py36h62672b6_0 conda-forge
    openssl:         1.0.2p-h14c3975_0    --> 1.0.2p-h470a237_0    conda-forge
<details>

```


```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : mssenv3
    active env location : /home/user/miniconda3/envs/mssenv3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /home/user/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/user/miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.5 Linux/4.4.0-134-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</details>

I had run in the problem that 1.4.0 works but 1.4.1 of netcdf4 doesn't 

https://bitbucket.org/wxmetvis/mss/issues/366/demodata-mswms-problem

currently a downgrade to 1.4.0 solves it for me.

**Comment by dopplershift** [comment]
Have you made sure you're running the latest libnetcdf?

**Comment by ocefpaf** [comment]
Can you provide a [sscce](http://sscce.org/) to help us debug this?

Also, it does not look like an issue with packaging. Please take a look at the issue tracker upstream for similar problems and check the package changelog.

**Comment by ReimarBauer** [comment]
I do look also upstream, this example shows what happens

The problem seemingly occurs, when a masked array is supplied that uses only a single boolean (np.ma.nomask) instead of a full boolean array.

```
import numpy as np
import netCDF4 as nc

a = np.asarray([0, 6, 12])
print(nc.num2date(a, "hours since 2012-10-17T12:00:00.000Z"))  # <- fine
b = np.ma.masked_invalid(a)
print(type(b), b.shape, b.mask)
print(nc.num2date(b, "hours since 2012-10-17T12:00:00.000Z"))  # <- fine
b = np.ma.asarray(a)
print(type(b), b.shape, b.mask)
print(nc.num2date(b, "hours since 2012-10-17T12:00:00.000Z"))  # <- Exception
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cftime/_cftime.pyx", line 290, in cftime._cftime.num2date
  File "cftime/_cftime.pyx", line 1211, in cftime._cftime.utime.num2date
  File "/home/user/miniconda3/envs/simmple/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/user/miniconda3/envs/simmple/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (3,)
```
see also https://github.com/Unidata/netcdf4-python/issues/847

**Comment by dopplershift** [comment]
Can you do `conda update -c conda-forge cftime` ? I think you're running an out-of-date version of `cftime`.

**Comment by ReimarBauer** [comment]
@dopplershift 
yeah, you are right. I guess we should have `cftime >=1.0.1` in netCDF 1.4.1
