### ISSUE TITLE
date

### ISSUE THREAD

**Issue by ReimarBauer** [conda-forge/netcdf4-feedstock#60]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
Closing this b/c there is no bug report and the title is rather cryptic :grimacing:

**Comment by ReimarBauer** [comment]
yep, not seen, that I have saved that. sorry.
