### ISSUE TITLE
Error: Library not loaded: @rpath/libssl.1.0.0.dylib #877

### ISSUE THREAD

**Issue by johnwoodill** [conda-forge/netcdf4-feedstock#73]
Issue: I am receiving the following error when trying to load the package.

`import netCDF4 as nc`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/john/miniconda3/lib/python3.6/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/john/miniconda3/lib/python3.6/site-packages/netCDF4/_netCDF4.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/john/miniconda3/lib/libssh2.1.dylib
  Reason: image not found
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1  
absl-py                   0.7.0                 py36_1000    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
appnope                   0.1.0                 py36_1000    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astor                     0.7.1                      py_0    conda-forge
astroid                   1.6.4                    pypi_0    pypi
attrs                     18.2.0                     py_0    conda-forge
automat                   0.7.0                      py_1    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
basemap                   1.2.0           py36h3f464f3_1001    conda-forge
blas                      1.0                         mkl  
bleach                    3.1.0                      py_0    conda-forge
bottleneck                1.2.1                    pypi_0    pypi
brewer2mpl                1.4.1                    pypi_0    pypi
bwidget                   1.9.11                        1  
bzip2                     1.0.6             h1de35cc_1002    conda-forge
c-ares                    1.15.0            h1de35cc_1001    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cachecontrol              0.12.5                   pypi_0    pypi
cairo                     1.14.12           h9d4d9ac_1005    conda-forge
cartopy                   0.17.0          py36h929c6f0_1004    conda-forge
cctools                   895                  h7512d6f_0    conda-forge
cement                    2.10.2                   pypi_0    pypi
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5          py36h342bebf_1001    conda-forge
cftime                    1.0.3.4         py36h917ab60_1000    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
clang                     4.0.1                h662ec87_0    conda-forge
clang_osx-64              4.0.1               h1ce6c1d_11    conda-forge
clangxx                   4.0.1                hc9b4283_0  
clangxx_osx-64            4.0.1               h22b1bf0_11  
cloog                     0.18.0                       10    conda-forge
cloudpickle               0.7.0                      py_0    conda-forge
compiler-rt               4.0.1                h5487866_0    conda-forge
conda                     4.6.4                    py36_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
constantly                15.1.0                     py_0    conda-forge
cryptography              2.5              py36ha12b0ac_0  
cryptography-vectors      2.5                        py_0    conda-forge
curl                      7.63.0            ha441bb4_1000  
cycler                    0.10.0                     py_1    conda-forge
cymem                     2.0.2                    pypi_0    pypi
cython                    0.29.5           py36h0a44026_0    conda-forge
cytoolz                   0.9.0.1                  pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
dbus                      1.13.0            h776b7f1_1000    conda-forge
decorator                 4.3.2                      py_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
dill                      0.2.9                    py36_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
elex                      2.4.4                    pypi_0    pypi
entrypoints               0.3                   py36_1000    conda-forge
expat                     2.2.5             h0a44026_1002    conda-forge
fastai                    1.0.32                   pypi_0    pypi
fastprogress              0.1.16                   pypi_0    pypi
feather-format            0.4.0                    pypi_0    pypi
fontconfig                2.13.1            h1e4e890_1000    conda-forge
freetype                  2.9.1             h597ad8a_1005    conda-forge
fribidi                   1.0.5             h1de35cc_1000    conda-forge
future                    0.17.1                   pypi_0    pypi
gast                      0.2.1.post0                py_0    conda-forge
gcc                       4.8.5                         8    conda-forge
geos                      3.7.1             h0a44026_1000    conda-forge
gettext                   0.19.8.1          hcca000d_1001    conda-forge
gfortran_osx-64           4.8.5                h22b1bf0_8    conda-forge
ggplot                    0.11.5                   pypi_0    pypi
glib                      2.56.2            h67dad55_1001    conda-forge
gmp                       5.1.2                         6    conda-forge
graphite2                 1.3.13            h2098e52_1000    conda-forge
graphviz                  2.38.0            hc6cc99f_1011    conda-forge
grpcio                    1.16.1           py36h044775b_1  
gsl                       2.4                  h1de35cc_4  
h5py                      2.9.0           nompi_py36h35dc34b_1102    conda-forge
harfbuzz                  1.9.0             h9889186_1001    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h646315f_1105    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
hyperlink                 17.3.1                     py_0    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2019.1                      144  
ipykernel                 5.1.0           py36h24bf2e0_1002    conda-forge
ipython                   7.2.0           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isl                       0.12.2                        1    conda-forge
isort                     4.3.4                    pypi_0    pypi
jedi                      0.13.2                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.4                   py36_0    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
keras                     2.2.2                    py36_0    conda-forge
keras-applications        1.0.4                      py_1    conda-forge
keras-base                2.2.2                    py36_0  
keras-preprocessing       1.0.2                      py_1    conda-forge
keyring                   17.1.1                py36_1000    conda-forge
kiwisolver                1.0.1           py36h04f5b5a_1002    conda-forge
krb5                      1.16.1               hddcf347_7  
lazy-object-proxy         1.3.1                    pypi_0    pypi
ld64                      274.2                h7c2db76_0    conda-forge
libcurl                   7.63.0            h051b688_1000  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h0a44026_1005    conda-forge
libgcc                    4.8.5               hdbeacc1_10    conda-forge
libgfortran               3.0.1                h93005f0_2  
libgpuarray               0.7.6             h1de35cc_1003    conda-forge
libiconv                  1.15              h1de35cc_1004    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libopenblas               0.3.3                hdc02c5d_3  
libpng                    1.6.36            ha441bb4_1000    conda-forge
libprotobuf               3.6.1             hd9629dc_1000    conda-forge
libsodium                 1.0.16            h1de35cc_1001    conda-forge
libssh2                   1.8.0                         1    conda-forge
libtiff                   4.0.10            h344961e_1002    conda-forge
libxcb                    1.13              h1de35cc_1002    conda-forge
libxml2                   2.9.8             hf14e9c8_1005    conda-forge
libxslt                   1.1.32            h33a18ac_1002    conda-forge
linearmodels              4.8                      pypi_0    pypi
llvm                      4.0.1                hc748206_0    conda-forge
llvm-lto-tapi             4.0.1                h6701bc3_0    conda-forge
llvm-openmp               4.0.1                hcfea43d_1  
lockfile                  0.12.2                   pypi_0    pypi
lxml                      4.3.1            py36h7166777_0    conda-forge
make                      4.2.1             h1de35cc_2004    conda-forge
mako                      1.0.7                      py_1    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.1.0           py36h1de35cc_1000    conda-forge
matplotlib                3.0.2                    pypi_0    pypi
matplotlib-base           3.0.2           py36hf043ca5_1002    conda-forge
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4           py36h1de35cc_1000    conda-forge
mizani                    0.5.3                    pypi_0    pypi
mkl                       2019.1                      144  
mkl_fft                   1.0.10                   py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
mock                      2.0.0                 py36_1000    conda-forge
mpc                       1.1.0                         5    conda-forge
mpfr                      4.0.1                         0    conda-forge
msgpack-numpy             0.4.3.2                    py_0    conda-forge
msgpack-python            0.6.1            py36h04f5b5a_0    conda-forge
murmurhash                1.0.1                    pypi_0    pypi
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
netcdf4                   1.4.2           py36hd700958_1001    conda-forge
notebook                  5.7.4                 py36_1000    conda-forge
numexpr                   2.6.8                    pypi_0    pypi
numpy                     1.15.4           py36hacdab7b_0  
numpy-base                1.15.4           py36h6575580_0  
numpydoc                  0.8.0                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             hdc02c5d_1001    conda-forge
opencv-python             3.4.1.15                 pypi_0    pypi
openssl                   1.1.1a            h1de35cc_1000    conda-forge
owslib                    0.17.1                     py_0    conda-forge
packaging                 19.0                       py_0    conda-forge
palettable                3.1.1                    pypi_0    pypi
pandas                    0.24.1           py36h0a44026_0    conda-forge
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               h060686c_0  
parso                     0.3.3                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pbr                       5.1.2                      py_0    conda-forge
pcre                      8.42                 h378b8a2_0  
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    5.3.0                    pypi_0    pypi
pip                       18.1                     pypi_0    pypi
pixman                    0.34.0            h1de35cc_1003    conda-forge
plac                      0.9.6                    pypi_0    pypi
plotly                    3.6.1                      py_0    conda-forge
plotnine                  0.5.1                      py_0    conda-forge
preshed                   2.0.1                    pypi_0    pypi
progressbar2              3.38.0                   pypi_0    pypi
proj4                     5.2.0             h1de35cc_1001    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.8                      py_0    conda-forge
protobuf                  3.6.1           py36h0a44026_1001    conda-forge
psutil                    5.5.0            py36h1de35cc_0    conda-forge
pthread-stubs             0.4               h1de35cc_1001    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pyarrow                   0.12.0                   pypi_0    pypi
pyasn1                    0.4.4                      py_1    conda-forge
pyasn1-modules            0.2.3                      py_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycosat                   0.6.3           py36h1de35cc_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.1.0                      py_0    conda-forge
pygam                     0.8.0                    pypi_0    pypi
pygments                  2.3.1                      py_0    conda-forge
pygpu                     0.7.6           py36h917ab60_1000    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pykdtree                  1.3.1           py36h917ab60_1002    conda-forge
pylint                    1.9.1                    pypi_0    pypi
pymongo                   3.3.0                    pypi_0    pypi
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.6           py36h9c430a6_1000    conda-forge
pyqt                      4.11.4                   py36_2    conda-forge
pyrsistent                0.14.10          py36h1de35cc_0    conda-forge
pyshp                     2.0.1                      py_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pystan                    2.17.1.0        py36h1702cab_1003    conda-forge
python                    3.6.8                haf84260_0  
python-dateutil           2.8.0                      py_0    conda-forge
python-graphviz           0.10.1                   pypi_0    pypi
python-utils              2.3.0                    pypi_0    pypi
python.app                1.2             py36h1de35cc_1200    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13            py36h1de35cc_1001    conda-forge
pyzmq                     17.1.2          py36h111632d_1001    conda-forge
qt                        4.8.7                         1    anaconda
qtawesome                 0.5.6              pyh8a2030e_0    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
qtpy                      1.6.0              pyh8a2030e_0    conda-forge
r-abind                   1.4_5           r351h6115d3f_1000    conda-forge
r-assertthat              0.2.0           r351h6115d3f_1001    conda-forge
r-backports               1.1.3           r351h46e59ec_1000    conda-forge
r-base                    3.5.1                h539fb6c_1  
r-base64enc               0.1_3           r351h46e59ec_1002    conda-forge
r-bh                      1.69.0_1         r351h6115d3f_0    conda-forge
r-bindr                   0.1.1           r351h6115d3f_1001    conda-forge
r-bindrcpp                0.2.2           r351h466af19_1001    conda-forge
r-bit                     1.1_12          r351h1de35cc_1002    conda-forge
r-bit64                   0.9_7           r351h46e59ec_1000    conda-forge
r-blob                    1.1.1                 r351_1001    conda-forge
r-boot                    1.3_20                r351_1000    conda-forge
r-broom                   0.5.1           r351h6115d3f_1000    conda-forge
r-callr                   3.1.1           r351h6115d3f_1000    conda-forge
r-caret                   6.0_81          r351h46e59ec_1000    conda-forge
r-cellranger              1.1.0           r351h6115d3f_1001    conda-forge
r-class                   7.3_15          r351h46e59ec_1000    conda-forge
r-cli                     1.0.1           r351h6115d3f_1000    conda-forge
r-clipr                   0.5.0            r351h6115d3f_0    conda-forge
r-cluster                 2.0.7_1         r351hfffe0aa_1000    conda-forge
r-codetools               0.2_16          r351h6115d3f_1000    conda-forge
r-colorspace              1.4_0            r351h46e59ec_0    conda-forge
r-crayon                  1.3.4           r351h6115d3f_1001    conda-forge
r-curl                    3.3              r351h46e59ec_0    conda-forge
r-cvst                    0.2_2           r351h6115d3f_1000    conda-forge
r-data.table              1.12.0           r351h46e59ec_0    conda-forge
r-dbi                     1.0.0           r351h6115d3f_1001    conda-forge
r-dbplyr                  1.3.0           r351h6115d3f_1000    conda-forge
r-ddalpha                 1.3.4           r351hbe7ee20_1001    conda-forge
r-deoptimr                1.0_8           r351h6115d3f_1001    conda-forge
r-dichromat               2.0_0                 r351_2000    conda-forge
r-digest                  0.6.18          r351h46e59ec_1000    conda-forge
r-dimred                  0.1.0           r351h6115d3f_1002    conda-forge
r-dplyr                   0.7.8           r351h466af19_1000    conda-forge
r-drr                     0.0.3           r351h6115d3f_1001    conda-forge
r-essentials              3.5.1                 r351_2000    conda-forge
r-evaluate                0.12            r351h6115d3f_1000    conda-forge
r-fansi                   0.4.0           r351h46e59ec_1000    conda-forge
r-forcats                 0.3.0           r351h6115d3f_1001    conda-forge
r-foreach                 1.4.4           r351h6115d3f_1001    conda-forge
r-foreign                 0.8_71          r351h46e59ec_1002    conda-forge
r-formatr                 1.5             r351h6115d3f_1001    conda-forge
r-fs                      1.2.6           r351h466af19_1000    conda-forge
r-generics                0.0.2           r351h6115d3f_1001    conda-forge
r-geometry                0.3_6           r351h46e59ec_1002    conda-forge
r-ggplot2                 3.1.0           r351h6115d3f_1000    conda-forge
r-gistr                   0.4.2           r351h6115d3f_1001    conda-forge
r-glmnet                  2.0_16          r351hfffe0aa_1001    conda-forge
r-glue                    1.3.0           r351h1de35cc_1002    conda-forge
r-gower                   0.1.2           r351h46e59ec_1002    conda-forge
r-gtable                  0.2.0           r351h6115d3f_1001    conda-forge
r-haven                   2.0.0           r351h466af19_1000    conda-forge
r-hexbin                  1.27.2          r351hfffe0aa_1002    conda-forge
r-highr                   0.7             r351h6115d3f_1001    conda-forge
r-hms                     0.4.2           r351h6115d3f_1000    conda-forge
r-htmltools               0.3.6           r351h0a44026_1002    conda-forge
r-htmlwidgets             1.3             r351h6115d3f_1000    conda-forge
r-httpuv                  1.4.5.1         r351h0a44026_1000    conda-forge
r-httr                    1.4.0           r351h6115d3f_1000    conda-forge
r-ipred                   0.9_8           r351h46e59ec_1000    conda-forge
r-irdisplay               0.7                   r351_1000    conda-forge
r-irkernel                0.8.15          r351h6115d3f_1001    conda-forge
r-iterators               1.0.10          r351h6115d3f_1001    conda-forge
r-jsonlite                1.6             r351h46e59ec_1000    conda-forge
r-kernlab                 0.9_27          r351h466af19_1000    conda-forge
r-kernsmooth              2.23_15         r351hfffe0aa_1002    conda-forge
r-knitr                   1.21            r351h6115d3f_1000    conda-forge
r-labeling                0.3             r351h6115d3f_1001    conda-forge
r-later                   0.7.5           r351h466af19_1000    conda-forge
r-lattice                 0.20_38         r351h46e59ec_1000    conda-forge
r-lava                    1.6.4           r351h6115d3f_1000    conda-forge
r-lazyeval                0.2.1           r351h46e59ec_1002    conda-forge
r-lubridate               1.7.4           r351h466af19_1001    conda-forge
r-magic                   1.5_8           r351h6115d3f_1000    conda-forge
r-magrittr                1.5             r351h6115d3f_1001    conda-forge
r-maps                    3.3.0           r351h46e59ec_1002    conda-forge
r-markdown                0.9             r351h46e59ec_1000    conda-forge
r-mass                    7.3_51.1        r351h46e59ec_1000    conda-forge
r-matrix                  1.2_15          r351h46e59ec_1000    conda-forge
r-memoise                 1.1.0           r351h6115d3f_1001    conda-forge
r-mgcv                    1.8_26          r351h46e59ec_1000    conda-forge
r-mime                    0.6             r351h46e59ec_1000    conda-forge
r-modelmetrics            1.1.0           r351h466af19_1002    conda-forge
r-modelr                  0.1.2           r351h6115d3f_1001    conda-forge
r-munsell                 0.5.0           r351h6115d3f_1001    conda-forge
r-nlme                    3.1_137         r351hfffe0aa_1000    conda-forge
r-nnet                    7.3_12          r351h46e59ec_1002    conda-forge
r-numderiv                2016.8_1        r351h6115d3f_1001    conda-forge
r-openssl                 1.0.2            r351h46e59ec_1  
r-pbdzmq                  0.3_3           r351hc3e5428_1000    conda-forge
r-pillar                  1.3.1           r351h6115d3f_1000    conda-forge
r-pkgconfig               2.0.2           r351h6115d3f_1001    conda-forge
r-plogr                   0.2.0           r351h6115d3f_1001    conda-forge
r-pls                     2.7_0           r351h6115d3f_1000    conda-forge
r-plyr                    1.8.4           r351h466af19_1002    conda-forge
r-praise                  1.0.0           r351h6115d3f_1001    conda-forge
r-prettyunits             1.0.2           r351h6115d3f_1001    conda-forge
r-processx                3.2.1           r351h46e59ec_1000    conda-forge
r-prodlim                 2018.04.18      r351h466af19_1002    conda-forge
r-progress                1.2.0           r351h6115d3f_1002    conda-forge
r-promises                1.0.1           r351h466af19_1000    conda-forge
r-pryr                    0.1.4           r351h466af19_1002    conda-forge
r-ps                      1.3.0           r351h46e59ec_1000    conda-forge
r-purrr                   0.2.5           r351h46e59ec_1002    conda-forge
r-quantmod                0.4_13          r351h6115d3f_1000    conda-forge
r-r6                      2.3.0           r351h6115d3f_1000    conda-forge
r-randomforest            4.6_14          r351hfffe0aa_1000    conda-forge
r-rbokeh                  0.5.0           r351h6115d3f_1001    conda-forge
r-rcolorbrewer            1.1_2           r351h6115d3f_1001    conda-forge
r-rcpp                    1.0.0           r351h466af19_1000    conda-forge
r-rcpproll                0.3.0           r351h466af19_1000    conda-forge
r-readr                   1.3.1           r351h466af19_1000    conda-forge
r-readxl                  1.2.0           r351h466af19_1000    conda-forge
r-recipes                 0.1.4           r351h6115d3f_1000    conda-forge
r-recommended             3.5.1                 r351_1001    conda-forge
r-rematch                 1.0.1           r351h6115d3f_1001    conda-forge
r-repr                    0.19.1          r351h6115d3f_1000    conda-forge
r-reprex                  0.2.1           r351h6115d3f_1000    conda-forge
r-reshape2                1.4.3           r351h466af19_1003    conda-forge
r-rlang                   0.3.1            r351h46e59ec_0    conda-forge
r-rmarkdown               1.11            r351h6115d3f_1000    conda-forge
r-robustbase              0.93_2          r351hfffe0aa_1000    conda-forge
r-rpart                   4.1_13          r351h46e59ec_1002    conda-forge
r-rprojroot               1.3_2           r351h6115d3f_1001    conda-forge
r-rsqlite                 2.1.1           r351h466af19_1000    conda-forge
r-rstudioapi              0.9.0            r351h6115d3f_0    conda-forge
r-rvest                   0.3.2           r351h6115d3f_1001    conda-forge
r-scales                  1.0.0           r351h466af19_1001    conda-forge
r-selectr                 0.4_1           r351h6115d3f_1000    conda-forge
r-sfsmisc                 1.1_2           r351h6115d3f_1000    conda-forge
r-shiny                   1.2.0                 r351_1000    conda-forge
r-sourcetools             0.1.7           r351h0a44026_1000    conda-forge
r-spatial                 7.3_11          r351h46e59ec_1002    conda-forge
r-squarem                 2017.10_1       r351h6115d3f_1001    conda-forge
r-stringi                 1.2.4           r351h466af19_1001    conda-forge
r-stringr                 1.3.1           r351h6115d3f_1001    conda-forge
r-survival                2.43_3          r351h46e59ec_1000    conda-forge
r-testthat                2.0.1           r351h466af19_1000    conda-forge
r-tibble                  2.0.1            r351h46e59ec_0    conda-forge
r-tidyr                   0.8.2           r351h466af19_1002    conda-forge
r-tidyselect              0.2.5           r351h466af19_1000    conda-forge
r-tidyverse               1.2.1           r351h6115d3f_1001    conda-forge
r-timedate                3043.102        r351h6115d3f_1000    conda-forge
r-tinytex                 0.10             r351h6115d3f_0    conda-forge
r-ttr                     0.23_4          r351hfffe0aa_1000    conda-forge
r-utf8                    1.1.4           r351h46e59ec_1000    conda-forge
r-uuid                    0.1_2           r351h46e59ec_1001    conda-forge
r-viridislite             0.3.0           r351h6115d3f_1001    conda-forge
r-whisker                 0.3_2           r351h6115d3f_1001    conda-forge
r-withr                   2.1.2           r351h6115d3f_1000    conda-forge
r-xfun                    0.4             r351h6115d3f_1000    conda-forge
r-xml2                    1.2.0           r351h466af19_1002    conda-forge
r-xtable                  1.8_3                 r351_2000    conda-forge
r-xts                     0.11_1          r351h46e59ec_1000    conda-forge
r-yaml                    2.2.0           r351h46e59ec_1001    conda-forge
r-zoo                     1.8_4           r351h46e59ec_1000    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
regex                     2018.11.22               pypi_0    pypi
requests                  2.19.1                   pypi_0    pypi
retrying                  1.3.3                      py_2    conda-forge
rope                      0.10.7                     py_1    conda-forge
rpy2                      2.9.4           py36r351h941a26a_1    conda-forge
ruamel_yaml               0.15.71         py36h1de35cc_1000    conda-forge
scikit-learn              0.20.2           py36h27c97d8_0  
scipy                     1.2.0            py36h1410ff5_0  
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setuptools                40.8.0                   py36_0    conda-forge
shapely                   1.6.4           py36h2bcc7ef_1002    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.12.0                py36_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
spacy                     2.0.16                   pypi_0    pypi
sphinx                    1.8.4                    py36_0    conda-forge
sphinxcontrib             1.0                      py36_1  
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder-kernels            0.4.2                    py36_0    conda-forge
sqlite                    3.26.0            h1765d9f_1000    conda-forge
statsmodels               0.9.0           py36h917ab60_1000    conda-forge
tensorboard               1.10.0                   py36_0    conda-forge
tensorflow                1.10.0                   py36_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
theano                    1.0.4           py36h0a44026_1000    conda-forge
thinc                     6.12.0                   pypi_0    pypi
tk                        8.6.9             ha441bb4_1000    conda-forge
tktable                   2.10                 h1de35cc_0  
toolz                     0.9.0                    pypi_0    pypi
torchvision-nightly       0.2.1                    pypi_0    pypi
tornado                   5.1.1           py36h1de35cc_1000    conda-forge
tqdm                      4.31.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
twisted                   18.9.0          py36h1de35cc_1000    conda-forge
typed-ast                 1.3.1            py36h1de35cc_0    conda-forge
typing                    3.6.6                    pypi_0    pypi
tzlocal                   1.5.1                      py_0    conda-forge
ujson                     1.35                     pypi_0    pypi
urllib3                   1.24.1                py36_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wget                      1.19.5               h051b688_0  
wheel                     0.33.0                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.10.11                  pypi_0    pypi
wurlitzer                 1.0.2                 py36_1000    conda-forge
xorg-kbproto              1.0.7             h1de35cc_1002    conda-forge
xorg-libice               1.0.9             h1de35cc_1004    conda-forge
xorg-libsm                1.2.3             h1de35cc_1000    conda-forge
xorg-libx11               1.6.7             h1de35cc_1000    conda-forge
xorg-libxau               1.0.9                h1de35cc_0    conda-forge
xorg-libxdmcp             1.1.2             h1de35cc_1007    conda-forge
xorg-libxext              1.3.3             h1de35cc_1004    conda-forge
xorg-libxrender           0.9.10            h1de35cc_1002    conda-forge
xorg-renderproto          0.11.1            h1de35cc_1002    conda-forge
xorg-xextproto            7.3.0             h1de35cc_1002    conda-forge
xorg-xproto               7.0.31            h1de35cc_1007    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zeromq                    4.2.5             h0a44026_1006    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zope                      1.0                      py36_1  
zope.interface            4.6.0           py36h1de35cc_1000    conda-forge
zstd                      1.3.3                         1    conda-forge

**Comment by ocefpaf** [comment]
I don't have a mac to test but based on the `conda list` you sent looks like you have a mix of channels that may be the culprit. See https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels for more information on the problem.

Depending on your conda version and the packages you need the solutions can be:

- remove `defaults` entirely from your `.condarc` and/or environment;
- try conda's latest `strict channel` feature, see [this `.condarc`](https://gist.github.com/ocefpaf/863fc5df6ed8444378fbb1211ad8feb1) for an example.


This works for me on Linux with the second suggestion there:

```
conda create --name TEST python=3.6 netcdf4
conda activate TEST
python -c 'import netCDF4; print(netCDF4.__version__)'
1.4.2
```

**Comment by ocefpaf** [comment]
I believe this one was fixed. Please re-open if you are still experiencing this issue.

**Comment by djgagne** [comment]
I ran into this same problem today. I had to manually update libssh2 to get `from netCDF4 import Dataset` to work properly. Updating netcdf4 did not trigger an update of libssh2. Is there a way to fix this dependency issue?

**Comment by ocefpaf** [comment]
@djgagne please open a new issue with the info equested in the issue template so we can debug this.

**Comment by djgagne** [comment]
See https://github.com/conda-forge/netcdf4-feedstock/issues/88.
